apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
annotations:
  ansible.operator-sdk/reconcile-period: "0s"
spec:
  template:
    spec:
      tolerations:
      - key: "kiali"
        operator: "Equal"
        value: "no"
        effect: "NoSchedule"
  auth:
    strategy: "anonymous"
  deployment:
    image_name: "kiali/kiali"
    image_pull_policy: "IfNotPresent"
    image_version: "dev"
    namespace: "istio-system"
    service_type: "NodePort"

  external_services:
    grafana:
      auth:
        ca_file: ""
        insecure_skip_verify: false
        password: ""
        token: ""
        type: "none"
        use_kiali_token: true
        username: ""
      enabled: true
      in_cluster_url: "http://grafana.istio-system:3000"
      url: "http://localhost:3000"
