apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
annotations:
  ansible.operator-sdk/reconcile-period: "0s"
spec:
  auth:
    strategy: "anonymous"
  deployment:
    image_name: "soda2019/aladdin"
    image_version: "jungeun"
